# Generated by Django 2.1.4 on 2018-12-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_label', models.CharField(max_length=50)),
                ('banner_description', models.TextField()),
                ('banner_image_pc', models.ImageField(upload_to='banner_images')),
                ('banner_image_mobile', models.ImageField(upload_to='banner_images')),
                ('banner_langding_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_telnum', models.CharField(max_length=11, unique=True)),
                ('customer_ktshop_id', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gift_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gift_detail', models.ImageField(blank=True, null=True, upload_to='gift_images')),
                ('gift_shopurl', models.URLField(null=True)),
                ('on_promotion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_ktshop_id', models.CharField(max_length=30)),
                ('device_invoice_num', models.CharField(max_length=20)),
                ('gift_invoice_num', models.CharField(max_length=20)),
                ('memo', models.TextField()),
                ('cfmd', models.BooleanField(default=False)),
                ('cncl', models.BooleanField(default=False)),
                ('expd', models.BooleanField(default=False)),
                ('device_send_date', models.DateField()),
                ('gift_order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('customer_telnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Customer')),
                ('gift_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Gift')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('device_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=20)),
                ('device_price', models.CharField(max_length=10)),
                ('device_image_url', models.URLField(null=True)),
                ('device_image_file', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('ktshop_link', models.CharField(default='', max_length=200)),
                ('on_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('combi_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=30)),
                ('color_name', models.CharField(max_length=20)),
                ('color_code', models.CharField(max_length=10)),
                ('color_modified_name', models.CharField(max_length=20, null=True)),
                ('color_modified_code', models.CharField(max_length=10, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('review_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_device_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Product')),
                ('review_writer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='recommender_telnum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Order'),
        ),
    ]
