# Generated by Django 2.1.4 on 2018-12-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_product_ktshop_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='device_imgs'),
        ),
    ]
