# Generated by Django 2.1.4 on 2018-12-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_auto_20181225_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='device_images'),
        ),
    ]
