# Generated by Django 2.1.4 on 2018-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_product_device_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_color',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
