# Generated by Django 2.1.4 on 2018-12-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_auto_20181226_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_ktshop_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phonenumber', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Customer')),
            ],
        ),
    ]
