# Generated by Django 2.1.4 on 2018-12-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('review_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product_color',
            name='color_modified_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product_color',
            name='color_modified_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_recommender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Customer'),
        ),
    ]
