branch-defaults:
  master:
    environment: Honeycomms-env-1
    group_suffix: null
environment-defaults:
  Honeycomms-env-1:
    branch: null
    repository: null
global:
  application_name: honeycomms
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
